const nombresProductos = [
  "Camiseta de algodón",
  "Zapatillas deportivas",
  "Reloj de pulsera",
  "Portátil ultrafino",
  "Auriculares inalámbricos",
  "Mochila resistente al agua",
  "Gafas de sol de diseñador",
  "Cámara digital compacta",
  "Silla ergonómica de oficina",
  "Batería externa de 10000 mAh",
  "Cafetera programable",
  "Smartphone de última generación",
  "Tableta gráfica profesional",
  "Televisor 4K de 55 pulgadas",
  "Teclado mecánico para juegos",
  "Pantalones vaqueros de moda",
  "Chaqueta impermeable",
  "Altavoz Bluetooth portátil",
  "Mouse óptico de alta precisión",
  "Impresora todo en uno",
  "Secador de cabello iónico",
  "Sartén antiadherente",
  "Set de herramientas de bricolaje",
  "Mesa de comedor extensible",
  "Tostadora de acero inoxidable",
  "Licuadora de alta velocidad",
  "Máquina de afeitar eléctrica",
  "Silla de camping plegable",
  "Bicicleta de montaña",
  "Robot aspirador inteligente",
  "Patineta eléctrica",
  "Collar de perlas elegante",
  "Bolso de cuero genuino",
  "Guitarra acústica de concierto",
  "Juego de maletas de viaje",
  "Lavadora de carga frontal",
  "Refrigerador de dos puertas",
  "Altavoz inteligente con asistente",
  "Lámpara de pie moderna",
  "Cepillo de dientes eléctrico",
  "Set de cuchillos de cocina",
  "Monitor de juegos curvado",
  "Sillón reclinable de cuero",
  "Bicicleta estática con pantalla",
  "Telescopio astronómico",
  "Silla de playa plegable",
  "Cuna convertible para bebé",
  "Cámara de acción resistente al agua",
  "Maleta de cabina con ruedas",
  "Mesa de billar profesional",
  "Teclado y mouse inalámbricos",
  "Termo de acero inoxidable",
  "Almohada de espuma viscoelástica",
  "Zapatos de running ligeros",
  "Funda de sofá elástica",
  "Juego de herramientas de jardín",
  "Aspiradora sin bolsa",
  "Máquina de ejercicio elíptica",
  "Batería recargable para cámara",
  "Reloj de fitness con GPS",
  "Horno de convección de encimera",
  "Candado de seguridad para bicicleta",
  "Collar de diamantes",
  "Mesa de picnic plegable",
  "Lavavajillas de acero inoxidable",
  "Teclado mecánico retroiluminado",
  "Cafetera espresso automática",
  "Set de tazas de café de porcelana",
  "Silla de ruedas ligera",
  "Taladro eléctrico de alta potencia",
  "Saco de dormir para camping",
  "Plancha de vapor profesional",
  "Ventilador de torre silencioso",
  "Reproductor de Blu-ray 4K",
  "Manta eléctrica con ajuste de calor",
  "Mesa de ping pong plegable",
  "Cámara de seguridad para el hogar",
  "Robot de cocina multifunción",
  "Bicicleta de carretera de carbono",
  "Laptop para juegos de alta gama",
  "Impresora láser monocromática",
  "Sistema de sonido envolvente",
  "Toallas de baño suaves",
  "Mesa de estudio para niños",
  "Estufa de inducción de alta eficiencia",
  "Sistema de cámaras de vigilancia",
  "Juego de cubiertos de acero inoxidable",
  "Teclado ergonómico dividido",
  "Lavadora de platos empotrable",
  "Máquina de coser electrónica",
  "Mesa de trabajo plegable",
  "Sofá cama convertible",
  "Escritorio de pie ajustable",
  "Juego de edredón de lujo",
  "Cepillo de pelo iónico",
  "Reloj de pulsera inteligente",
  "Taburetes de bar modernos",
  "Bolso de viaje con ruedas",
  "Sistema de sonido portátil",
  "Set de batería acústica",
  "Cama king-size con dosel",
  "Horno de microondas de acero inoxidable",
  "Mesa de centro de vidrio",
  "Escaladora de fitness",
  "Cámara réflex digital",
  "Mochila de senderismo resistente",
  "Silla de oficina ergonómica",
  "Sistema de filtración de agua",
  "Máquina de waffles con forma",
  "Bolso cruzado de cuero",
  "Laptop convertible con pantalla táctil",
  "Aspiradora robot con mapeo",
  "Mesa de billar plegable",
  "Teclado mecánico compacto",
  "Sistema de altavoces inalámbricos",
  "Bicicleta eléctrica de montaña",
  "Lámpara de techo moderna",
  "Cepillo de dientes eléctrico sónico",
  "Set de cuchillos de chef",
  "Monitor de pantalla curvada",
  "Sofá seccional de cuero",
  "Cinta de correr plegable",
  "Telescopio terrestre compacto",
  "Silla de camping con reposabrazos",
  "Cuna portátil para bebé",
  "Cámara de acción 360 grados",
  "Maleta de viaje con ruedas giratorias",
  "Mesa de ajedrez de lujo",
  "Teclado y mouse ergonómicos",
  "Termo aislado de acero inoxidable",
  "Almohada de plumas suaves",
  "Zapatillas de running de alto rendimiento",
  "Funda de sofá resistente al agua",
  "Herramientas de jardinería de calidad",
  "Aspiradora robot con mapeo láser",
  "Máquina de ejercicio de cardio",
  "Batería recargable de larga duración",
  "Reloj de fitness con monitor de salud",
  "Horno de convección de encimera de lujo",
  "Candado de seguridad para bicicleta",
  "Collar de perlas cultivadas",
];

const descripcionesProductos = [
  "Una camiseta de algodón suave y cómoda para uso diario.",
  "Zapatillas deportivas de alto rendimiento ideales para correr y hacer ejercicio.",
  "Un elegante reloj de pulsera con diseño moderno y funcionalidad precisa.",
  "Un portátil ultrafino con potencia y portabilidad excepcionales.",
  "Auriculares inalámbricos con calidad de sonido premium.",
  "Mochila resistente al agua para llevar tus pertenencias de forma segura en cualquier clima.",
  "Gafas de sol de diseñador para un estilo elegante y protección UV.",
  "Cámara digital compacta con capacidades avanzadas de fotografía.",
  "Silla ergonómica de oficina para una comodidad prolongada.",
  "Una batería externa de 10000 mAh para mantener tus dispositivos cargados sobre la marcha.",
  "Cafetera programable que prepara café delicioso a tu gusto.",
  "Smartphone de última generación con todas las funciones que necesitas.",
  "Tableta gráfica profesional para diseñadores y artistas digitales.",
  "Televisor 4K de 55 pulgadas para una experiencia de visualización impresionante.",
  "Teclado mecánico para juegos con retroiluminación RGB y respuesta táctil.",
  "Pantalones vaqueros de moda con un ajuste moderno y cómodo.",
  "Chaqueta impermeable para mantenerte seco en días lluviosos.",
  "Altavoz Bluetooth portátil para disfrutar de la música en cualquier lugar.",
  "Mouse óptico de alta precisión para una navegación suave.",
  "Impresora todo en uno para imprimir, escanear y copiar documentos con facilidad.",
  "Secador de cabello iónico para un secado rápido y sin encrespamiento.",
  "Una sartén antiadherente para cocinar sin esfuerzo y sin que los alimentos se peguen.",
  "Un set de herramientas de bricolaje con todo lo necesario para proyectos en casa.",
  "Una mesa de comedor extensible para acomodar a tus invitados con estilo.",
  "Una tostadora de acero inoxidable que tuesta el pan de manera uniforme y crujiente.",
  "Licuadora de alta velocidad para preparar batidos y jugos frescos en segundos.",
  "Una máquina de afeitar eléctrica para un afeitado suave y sin irritaciones.",
  "Una silla de camping plegable para actividades al aire libre.",
  "Bicicleta de montaña resistente para aventuras en terrenos difíciles.",
  "Robot aspirador inteligente para mantener tu hogar limpio sin esfuerzo.",
  "Patineta eléctrica para desplazamientos rápidos y ecológicos.",
  "Collar de perlas elegante que añade un toque de sofisticación a cualquier atuendo.",
  "Bolso de cuero genuino con amplio espacio de almacenamiento.",
  "Guitarra acústica de concierto para músicos aficionados y profesionales.",
  "Juego de maletas de viaje duraderas y con ruedas para facilitar el transporte.",
  "Lavadora de carga frontal eficiente en energía y agua.",
  "Refrigerador de dos puertas con amplio espacio de almacenamiento.",
  "Altavoz inteligente con asistente virtual integrado para controlar tu hogar.",
  "Lámpara de pie moderna que ilumina tu espacio con estilo.",
  "Cepillo de dientes eléctrico para una limpieza dental efectiva.",
  "Set de cuchillos de cocina de alta calidad para preparar alimentos con precisión.",
  "Monitor de juegos curvado para una experiencia de juego inmersiva.",
  "Sillón reclinable de cuero para relajarte después de un largo día.",
  "Bicicleta estática con pantalla digital para mantenerse en forma en casa.",
  "Telescopio astronómico para observar el cielo nocturno.",
  "Silla de playa plegable para días de descanso en la playa.",
  "Cuna convertible para bebé que crece con tu hijo.",
  "Cámara de acción resistente al agua para capturar aventuras al aire libre.",
  "Maleta de cabina con ruedas para viajes cortos.",
  "Mesa de billar profesional para entretenimiento en casa.",
  "Teclado y mouse inalámbricos para una experiencia de computación sin cables.",
  "Termo de acero inoxidable para mantener las bebidas calientes o frías.",
  "Almohada de espuma viscoelástica para un sueño cómodo.",
  "Zapatos de running ligeros diseñados para correr con comodidad y velocidad.",
  "Funda de sofá elástica para proteger y decorar tu sofá.",
  "Juego de herramientas de jardín para el cuidado de tus plantas.",
  "Aspiradora sin bolsa para una limpieza eficiente del hogar.",
  "Máquina de ejercicio elíptica para entrenamientos cardiovasculares efectivos.",
  "Batería recargable para cámara para no perder nunca un momento especial.",
  "Reloj de fitness con GPS para llevar un seguimiento de tus actividades.",
  "Horno de convección de encimera para cocinar de manera uniforme y rápida.",
  "Candado de seguridad para bicicleta para proteger tu inversión.",
  "Collar de diamantes elegante que deslumbra en ocasiones especiales.",
  "Mesa de picnic plegable para disfrutar de comidas al aire libre.",
  "Lavavajillas de acero inoxidable para una limpieza de vajilla eficiente.",
  "Teclado mecánico retroiluminado para una experiencia de escritura única.",
  "Cafetera espresso automática para preparar café de alta calidad en casa.",
  "Set de tazas de café de porcelana para servir tus bebidas con estilo.",
  "Silla de ruedas ligera y cómoda para movilidad y comodidad.",
  "Taladro eléctrico de alta potencia para proyectos de bricolaje.",
  "Saco de dormir para camping que te mantiene cálido en noches frías.",
  "Plancha de vapor profesional para un planchado eficiente y sin arrugas.",
  "Ventilador de torre silencioso para mantener tu hogar fresco y tranquilo.",
  "Reproductor de Blu-ray 4K para una calidad de imagen excepcional.",
  "Manta eléctrica con ajuste de calor para mantenerse abrigado en invierno.",
  "Mesa de ping pong plegable para juegos divertidos en casa.",
  "Cámara de seguridad para el hogar para proteger tu propiedad.",
  "Robot de cocina multifunción para simplificar la preparación de alimentos.",
  "Bicicleta de carretera de carbono diseñada para velocidades altas.",
  "Laptop para juegos de alta gama para jugadores entusiastas.",
  "Impresora láser monocromática para impresiones rápidas y nítidas.",
  "Sistema de sonido envolvente para una experiencia de audio inmersiva.",
  "Toallas de baño suaves y absorbentes para tu rutina de baño.",
  "Mesa de estudio para niños con espacio de almacenamiento.",
  "Estufa de inducción de alta eficiencia para cocinar con precisión.",
  "Sistema de cámaras de vigilancia para proteger tu hogar y propiedad.",
  "Juego de cubiertos de acero inoxidable para comidas elegantes.",
  "Teclado ergonómico dividido para una escritura cómoda.",
  "Lavavajillas empotrable para una cocina con un aspecto limpio y ordenado.",
  "Máquina de coser electrónica para proyectos de costura creativos.",
  "Mesa de trabajo plegable para proyectos de bricolaje y manualidades.",
  "Sofá cama convertible para aprovechar al máximo el espacio en tu hogar.",
  "Escritorio de pie ajustable para una ergonomía personalizada.",
  "Juego de edredón de lujo para un descanso reparador.",
  "Cepillo de pelo iónico para un cabello suave y sin frizz.",
  "Reloj de pulsera inteligente con seguimiento de actividad y notificaciones.",
  "Taburetes de bar modernos para complementar tu barra o isla de cocina.",
  "Bolso de viaje con ruedas para llevar tus pertenencias con facilidad.",
  "Sistema de sonido portátil para disfrutar de la música en cualquier lugar.",
  "Set de batería acústica para músicos y bateristas aficionados.",
  "Cama king-size con dosel para un dormitorio elegante y espacioso.",
  "Horno de microondas de acero inoxidable para calentar y cocinar rápidamente.",
  "Mesa de centro de vidrio para una decoración contemporánea.",
  "Escaladora de fitness para ejercicios cardiovasculares efectivos.",
  "Cámara réflex digital para fotografía de alta calidad.",
  "Mochila de senderismo resistente para aventuras al aire libre.",
  "Silla de oficina ergonómica para una comodidad durante todo el día.",
  "Sistema de filtración de agua para agua potable limpia y saludable.",
  "Máquina de waffles con forma para desayunos divertidos.",
  "Bolso cruzado de cuero para llevar tus pertenencias con estilo.",
  "Portátil convertible con pantalla táctil para versatilidad en la computación.",
  "Aspiradora robot con mapeo para una limpieza eficiente y programable.",
  "Mesa de billar plegable para entretenimiento en el hogar.",
  "Teclado mecánico compacto para escritura precisa y rápida.",
  "Sistema de altavoces inalámbricos para un sonido de alta fidelidad sin cables.",
  "Bicicleta eléctrica de montaña para aventuras todoterreno.",
  "Lámpara de techo moderna para iluminar tu espacio con estilo.",
  "Cepillo de dientes eléctrico sónico para una limpieza dental avanzada.",
  "Set de cuchillos de chef para preparar alimentos con precisión.",
  "Monitor de pantalla curvada para una experiencia de visualización envolvente.",
  "Sofá seccional de cuero para una sala de estar elegante y cómoda.",
  "Cinta de correr plegable para entrenamientos en casa sin ocupar mucho espacio.",
  "Telescopio terrestre compacto para observar la naturaleza y la fauna.",
  "Silla de camping con reposabrazos para relajarse en el exterior.",
  "Cuna portátil para bebé para viajes y estancias fuera de casa.",
  "Cámara de acción 360 grados para capturar vistas panorámicas impresionantes.",
  "Maleta de viaje con ruedas giratorias para viajar con facilidad.",
  "Mesa de ajedrez de lujo para partidas de ajedrez emocionantes.",
  "Teclado y mouse ergonómicos para una comodidad en la computadora.",
  "Termo aislado de acero inoxidable para mantener las bebidas calientes o frías.",
  "Almohada de plumas suaves para un descanso de lujo.",
  "Zapatillas de running de alto rendimiento para correr con comodidad y velocidad.",
  "Funda de sofá resistente al agua para proteger tu sofá de derrames y manchas.",
  "Herramientas de jardinería de calidad para cuidar tu jardín con eficacia.",
  "Aspiradora robot con mapeo láser para una limpieza precisa y autónoma.",
  "Máquina de ejercicio de cardio para mantenerse en forma en casa.",
  "Batería recargable de larga duración para alimentar tus dispositivos.",
  "Reloj de fitness con monitor de salud para llevar un seguimiento de tu bienestar.",
  "Horno de convección de encimera de lujo para cocinar con estilo.",
  "Candado de seguridad para bicicleta para proteger tu inversión.",
  "Collar de perlas cultivadas para un aspecto elegante y sofisticado.",
];

const div_productos = document.querySelector(".productos");

conjunto_productos = "";

for (i = 0; i < nombresProductos.length; i++) {

  nombre = nombresProductos[i];
  descripcion = descripcionesProductos[i];

  conjunto_productos += `<div class="card producto" id="product-${i}">
    <img class="card-img-top" src="img/product.png" alt="imagen no encontrada">
    <div class="card-body">
        <h5 class="card-title">${nombre}</h5>
        <p class="card-text">${descripcion}</p>
    </div>
    </div>
    `;
}
div_productos.innerHTML = conjunto_productos